export {
  GET_BLOG_LIST,
  GET_LATEST_BLOG,
  GET_BLOG_POST,
  GET_EVENTS,
  GET_EVENT_POST,
  GET_SERVICES_POST,
  GET_BRANDS,
  GET_TEAM,
  GET_PRODUCTS_CATEGORIES_LIST,
  GET_PRODUCTS_CATEGORIES,
  GET_PRODUCTS_SUB_CATEGORIES,
  GET_PRODUCT_Detail,
} from "./Query";
